ct_mongodb
almaops/ansible-collection-common pull request #1
Opened 2022-12-01 13:40 UTC by hDw1z

Changes to be committed:
	new file:   ct_mongodb/LICENSE
	new file:   ct_mongodb/defaults/main.yml
	new file:   ct_mongodb/meta/main.yml
	new file:   ct_mongodb/tasks/main.yml

2022-12-03 14:04 UTC, freehck commented on roles/ct_mongodb/README.md
> +# almaops.ct_mongodb
ты добавляешь роль в коллекцию almaops.common

Тут должно быть almaops.common.ct_mongodb

2022-12-03 14:05 UTC, freehck commented on roles/ct_mongodb/README.md
> +    - role: "ct_mongodb"
аналогично: almaops.common.ct_mongodb

2022-12-03 14:10 UTC, freehck commented
@ussrlongbow 
можно было бы ещё добавить параметризацию `_evn`, но это в целом не обязательно
считаю, что можно мерджить

2022-12-05 07:30 UTC, hDw1z commented
Предлагаю пока не утверждать PR. Конфигурация ansible-роли ct_mongodb меняется. Пробую состыковать с ролью ct_rocketchat без дополнительной docker-сети.

2022-12-07 11:23 UTC, hDw1z commented
Замечания устранены. Заменил стандартный образ mongo на bitnami/mongodb, чтобы сделать его более универсальным, в частности, применимым к развертыванию Rocket.Chat'а.

2022-12-07 11:55 UTC, ussrlongbow requested changes

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/defaults/main.yml
> +# ct_mongodb_ct_bind_addr: "127.0.0.1"
Переменные вида `ct_mongodb_ct_*` определяют конфигурацию внутри контейнера.
Переменная `ct_mongodb_ct_bind_addr` не имеет смысла, потому что в контейнере приложение должно биндиться на 0.0.0.0

Эту переменную надо убрать

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/meta/main.yml
> +
надо убрать лишние строки

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/defaults/main.yml
> +
Все YAML файлы должны быть обособлены началом документа (`---`) и концом документа (`...`)
пример - https://github.com/almaops/ansible-collection-common/blob/master/roles/ct_minio/meta/main.yml#L1

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/defaults/main.yml
> +ct_mongodb_out_path_config: "/srv/{{ ct_mongodb_ct_name }}"
Что такое `_out_`?

Все переменные, которые содержат в себе пути на файловой системе сервера, где запускается контейнер, должны именоваться по маске `ct_mongodb_path_*`

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/defaults/main.yml
> +  MONGODB_INITDB_ROOT_USERNAME: "root"
Переменные окружения надо вынести в файл
`templates/mongodb.env.j2`

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/tasks/main.yml
> +    owner: 1001
`owner` надо определить в переменной

2022-12-07 11:55 UTC, ussrlongbow commented on roles/ct_mongodb/tasks/main.yml
> +  file:
Надо использовать FQCN - `ansible.builtin.file`

2022-12-07 13:25 UTC, hDw1z commented
Замечания устранены.
Итоговый коммит
https://github.com/almaops/ansible-collection-common/pull/1/commits/96c531cefa2dbe5dc7f2c86b41feec0075ad46a7

2022-12-07 13:35 UTC, ussrlongbow approved these changes
looks nice, approved

2022-12-07 13:36 UTC, merged