Ct rocketchat
almaops/ansible-collection-common pull request #3
Opened 2022-12-15 08:48 UTC by hDw1z

2022-12-16 09:54 UTC, ussrlongbow requested changes

2022-12-16 09:54 UTC, ussrlongbow commented on README.md
> +<<<<<<< HEAD
Убрать, артефакт остался от мержа

2022-12-16 09:54 UTC, ussrlongbow commented on README.md
> +>>>>>>> origin/master
Убрать, артефакт остался от мержа

2022-12-16 09:54 UTC, ussrlongbow commented on README.md
> +<<<<<<< HEAD
Убрать, артефакт остался от мержа

2022-12-16 09:54 UTC, ussrlongbow commented on README.md
> +=======
Убрать, артефакт остался от мержа

2022-12-16 09:54 UTC, ussrlongbow commented on README.md
> +>>>>>>> origin/master
Убрать, артефакт остался от мержа

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/README.md
> +# Dependencies
Какие зависимости и зачем?

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +ct_rocketchat_path_data: "/app"
Видимо должно было быть `{{ ct_rocketchat_path_data_base }}/app`

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +# ct_rocketchat_bind_ct_port: "3000"
Зачем закомментировано?

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +ct_rocketchat_ct_name: "rocket.chat-{{ ct_rocketchat_ct_version }}"
В названии контейнера не должно быть версии

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +ct_rocketchat_env_mongo_oplog_url: "mongodb://{{ ct_bitnami_mongodb_ct_name }}:{{ ct_bitnami_mongodb_bind_port }}/local?replicaSet={{ ct_bitnami_mongodb_env_mongodb_replica_set_name }}"
Здесь не должно быть зависимостий от переменных других ролей, потому что MongoDB может быть развёрнута иным способом

2022-12-16 09:54 UTC, ussrlongbow commented on roles/ct_rocketchat/tasks/main.yml
> +    group: 999
`owner` и `group` должны определяться через переменные

2022-12-16 11:14 UTC, hDw1z commented on roles/ct_rocketchat/defaults/main.yml
> +ct_rocketchat_path_data: "/app"
Не, всё ок. Делал по аналогии с ролью "ct_mongodb".

2022-12-16 11:26 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +ct_rocketchat_path_data: "/app"
Нет, это не тоже самое
все пути в переменных `<role_name>_path_*` должны быть абсолютными

2022-12-16 14:53 UTC, hDw1z commented
Замечания устранены. Добавлен [коммит](https://github.com/almaops/ansible-collection-common/pull/3/commits/fcf1f32a2e4b8784361f3a09112c501e1d3ae54a).

2022-12-19 15:32 UTC, ussrlongbow requested changes

2022-12-19 15:32 UTC, ussrlongbow commented on roles/ct_rocketchat/meta/main.yml
> +  description: Corporate chat of the company "{{ ct_rocketchat_company_name }}". The role was created based on the "rocket.chat" docker image from https://hub.docker.com
Зачем в описании роли использовать переменную? надо укоротить

например
`Role deploys a Rocketchat container from official Docker Hub image`

2022-12-19 15:32 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +# ct_rocketchat_env_root_url: "https://rocketchat.company.ru"
Вообще принято использовать example.com в качестве домена

2022-12-19 15:32 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +# ct_rocketchat_env_root_url: "https://rocketchat.company.ru"
То есть `https://rocketchat.example.com`

2022-12-19 15:32 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +  - "{{ ct_rocketchat_path_data_uploads }}/{{ ct_rocketchat_path_ct_data_uploads }}"
Опечатка, должно быть `:` вместо `/`

2022-12-19 15:32 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +# ct_rocketchat_mongodb_replica_set_name: "{{ ct_bitnami_mongodb_env_mongodb_replica_set_name }}"
Убрать ссылки на переменные из другой роли, в значении переменной должны быть примеры значений

2022-12-21 10:06 UTC, hDw1z commented
Замечания устранены. Добавлен [коммит](https://github.com/almaops/ansible-collection-common/pull/3/commits/fc14d7f71171b2db0d7192a2d9ee79339dedbade).

2022-12-21 10:50 UTC, ussrlongbow requested changes

2022-12-21 10:50 UTC, ussrlongbow commented on roles/ct_rocketchat/templates/rocketchat.env.j2
> +OVERWRITE_SETTING_LDAP_Username_Field={{ ct_rocketchat_env_overwrite_setting_ldap_username_field }}
вот весь этот блок имеет смысл обособить оператором if

примерно так:
```
{% if ct_rocketchat_env_overwrite_setting_ldap_enable %}
OVERWRITE_SETTING_LDAP_***
...
{% endif %}
```

2022-12-21 10:50 UTC, ussrlongbow commented on roles/ct_rocketchat/defaults/main.yml
> +# ct_rocketchat_env_overwrite_setting_ldap_enable: "true"
здесь поставить дефолтное значение false и убрать из комментария

2022-12-21 11:12 UTC, hDw1z commented
Замечания устранены. Добавлен [коммит](https://github.com/almaops/ansible-collection-common/pull/3/commits/0410503d35cdc134aaa49e8ea38b8acb84385cb3).

2022-12-21 11:15 UTC, ussrlongbow approved these changes
вроде всё ок

2022-12-21 11:18 UTC, merged